# Generated by Django 4.1.7 on 2023-02-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_t',
            name='created',
        ),
        migrations.AddField(
            model_name='test_t',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test_t',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
