# Generated by Django 4.1.6 on 2023-05-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdo_app', '0003_alter_service_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdo_app.organisation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdo_app.person'),
        ),
    ]
