# Generated by Django 4.1.6 on 2023-05-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdo_app', '0004_alter_service_provider_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativework',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='creativework',
            name='publisher',
        ),
        migrations.AddField(
            model_name='creativework',
            name='creator_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdo_app.organisation'),
        ),
        migrations.AddField(
            model_name='creativework',
            name='creator_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fdo_app.person'),
        ),
    ]
