# Generated by Django 4.1.7 on 2023-06-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdo_app', '0005_remove_creativework_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='creator_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fdo_app.organisation'),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='creator_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fdo_app.person'),
        ),
    ]
