# Generated by Django 4.1.7 on 2023-06-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdo_app', '0007_alter_creativework_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='identifier',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='identifier',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='identifier',
            field=models.TextField(max_length=200),
        ),
    ]
