# Generated by Django 4.1.7 on 2023-06-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdo_app', '0010_alter_creativework_name_alter_organisation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
